### ISSUE TITLE
XSLT current()

### ISSUE THREAD

**Issue by seamusmacgp** [ChrisTrenkamp/goxpath#9] opened 2017-06-14 15:54 UTC
I've been doing some work on goxpath, using it to evaluate xpath expressions used in the YANG data modelling language. I've been able to implement the tree.Node interface on top of my own store (I'm not using the XML parse part). I've been able to get a number of XPATH queries to work in this way.

One issue I just hit is the XSLT current() function is used in the YANG files, this fails to evaluate as current() isn't included in the implementation. Did you consider implementing current() at all ?

**Comment by ChrisTrenkamp** [comment] 2017-06-14 19:26
I have no intentions of implementing anything beyond the XPath 1.0 spec, but you can implement your own functions.

As for the current() method, I would instead [pass in a variable to your Exec call](https://github.com/ChrisTrenkamp/goxpath/wiki/API-Guide#registering-variables).  This should give you the functionality you're looking for.

**Comment by seamusmacgp** [comment] 2017-06-15 11:02
Hi Chris,

The XPATH expressions are part of a type of standard (OpenConfig), there is
sample XML and XPATH below. I would have thought that I needed change the
expressions to use a variable, but as they're part of a standard what we
don't control that isn't really practical.

As for the function this is what I'd been working with ok, but I'd expect
that the function will need something in the context to allow it to pickup
up the current node, also we can't return a tree.Node because it's not a
stringer, and should need to either considering current() is going to
following by something ../ (as in my example).

I'm not sure that the API is setup to allow such a function to be written.
Here is my example, I picked c.NodeSet[0] a bit arbitrarily but in my
examples it had the node I needed. In any case this fails as I mentioned:

./current.go:44: cannot use c.NodeSet[0] (type tree.Node) as type
tree.Result in return argument:
tree.Node does not implement tree.Result (missing String method)

But even it it could compile, I'm not sure that the could would be able to
so anything with it.

package main

import (
"bytes"
"encoding/xml"
"fmt"

"github.com/ChrisTrenkamp/goxpath"
"github.com/ChrisTrenkamp/goxpath/tree"
"github.com/ChrisTrenkamp/goxpath/tree/xmltree"
)

var xmlStr = xml.Header + `
<root>
  <video>
    <v-ip>0.0.0.0</v-ip>
    <v-port>0000</v-port>
    <v-stream>0|0|0|0</v-stream>
  </video>
  <client>
    <ip>0.0.0.0</ip>
    <port>0000</port>
    <stream>0|0|0|0</stream>
  </client>
  <client>
    <ip>0.0.0.1</ip>
    <port>0001</port>
    <stream>0|0|0|1</stream>
  </client>
  <client>
    <ip>0.0.0.2</ip>
    <port>0002</port>
    <stream>0|0|0|0</stream>
  </client>
  <client>
    <ip>0.0.0.2</ip>
    <port>0000</port>
    <stream>0|0|0|2</stream>
  </client>
</root>
`

func currentFunc(c tree.Ctx, args ...tree.Result) (tree.Result, error) {
return c.NodeSet[0], nil
}

var xpExec = goxpath.MustParse(`/client[ip=current()/../v-ip]/port`)

func main() {
xTree, err := xmltree.ParseXML(bytes.NewBufferString(xmlStr))
if err != nil {
panic(err)
}

res, err := xpExec.ExecNode(xTree, func(o *goxpath.Opts) {
o.NS["example"] = "http://example.com"
o.Funcs[xml.Name{Space: o.NS["example"], Local: "current"}] = tree.Wrap{Fn:
currentFunc, NArgs: 0}
})
if err != nil {
panic(err)
}

fmt.Printf("res=%#v")
}

**Comment by ChrisTrenkamp** [comment] 2017-06-18 14:32
The function needs to wrap the return value with tree.NodeSet; it'll compile, but still won't work.

The problem is this XPath expression is 2.0, not 1.0.  Function calls cannot have a path expression after it in 1.0.  XPath 2.0 does allow this, but the expression you posted is using XSLT extensions.

You should file a bug report with the OpenConfig people and get some clarification on the XPath version they're using.  The example you posted is a weird combination of XPath 2.0 with XSLT functions.

There are technical reasons for not allowing path expressions after function calls.  See if the OpenConfig people will reconsider their XPath expressions.

**Comment by seamusmacgp** [comment] 2017-06-20 09:01
H Chris,

I looked up the specs, and it isn't really an OpenConfig issue.
Unfortunately the expressions come from OpenConfig datamodels based on YANG
and the YANG RFC6020 spec specifically calls for XPATH 1.0 + the current()
function. So the OpenConfig guys are just developing expressions based on
YANG RFC6020.

I can still use goxpath for NETCONF XPATH expressions, which is what I
originally wanted anyway.

Thanks for your help and for goxpath.

**Comment by ChrisTrenkamp** [comment] 2017-06-20 11:28
[https://tools.ietf.org/html/rfc6020#section-6.4.1](https://tools.ietf.org/html/rfc6020#section-6.4.1)

Okay, I see why that current() function is in there, but goxpath still cannot combine functions with path expressions.  I'll see if there's a way to combine function calls with path expressions like the above example sometime this weekend.

**Comment by seamusmacgp** [comment] 2017-06-20 11:30
ok great, it would allow me to unify my work around a single API.
Thx

**Comment by ChrisTrenkamp** [comment] 2017-06-25 21:55
You can have path expressions after functions now (but not vice-versa).  Let me know if this fixes your use case.

**Comment by seamusmacgp** [comment] 2017-06-26 16:27
I tried out the latest version of the code. I implemented a current function to return the start node. This seems to work fine and gives the correct result.

Thanks a lot for looking at this.

**Comment by ChrisTrenkamp** [comment] 2017-06-26 22:15
Good to hear.  Closing.

**Closed by ChrisTrenkamp** 2017-06-26 22:15 UTC
